### ISSUE TITLE
Documentation Search

### ISSUE THREAD

**Issue by jgarte** [creatorrr/emacs-mint-mode#11]
One approach to [documentation search](https://github.com/creatorrr/emacs-mint-mode#planned-roadmap) can be to construct the URL for thing at point and open the relevant page in the browser using `xdg-open`, etc.

We would need to construct urls like the following for that approach:

- `https://mint-lang.com/api/components/Unless#children`
- `https://mint-lang.com/api/modules/Bool`
- `https://mint-lang.com/api/enums/Storage.Error`
- `https://mint-lang.com/api/components/Html.Portals.Head`
- `https://mint-lang.com/api/records/WebSocket.Config`
- `https://mint-lang.com/api/providers/Provider.WebSocket`
- `https://mint-lang.com/api/records/Provider.ElementSize.Subscription`

The other approach is to test how well `mint ls` is providing documentation and use that.

@zw963 @creatorrr WDYT

**Comment by zw963** [comment]
Sorry,  in fact, I know very little about how to integrate with LSP and emacs LISP.

Although, the format on save feature, document feature and completion all available for me after enable lsp.

![image](https://user-images.githubusercontent.com/549126/189591713-99c8a09d-583f-4beb-b284-cad1185abd0f.png)

![image](https://user-images.githubusercontent.com/549126/189592041-ff5da33c-b5ea-4c5c-89d2-003a07051c93.png)

**Comment by jgarte** [comment]
> Although, the format on save feature, document feature and completion all available for me after enable lsp.

@zw963 That's great to hear. So, then maybe we shouldn't support those features here and outsource it to the mint language server.

What do you think?

**Comment by zw963** [comment]
For the document feature,  i think yes.

**Comment by jgarte** [comment]
Closing this issue as documentation will be provided by `mint ls`. Thank you!
