### ISSUE TITLE
Is this repo still in development/accepting pull requests?

### ISSUE THREAD

**Issue by jgarte** [creatorrr/emacs-mint-mode#2]
Is this repo still in development/accepting pull requests?

**Comment by creatorrr** [comment]
Not able to maintain this actively anymore. However, I’m happy to hand it over if you’d like to take over

**Comment by jgarte** [comment]
> @jgarte @ryanprior not able to maintain this project actively anymore. Would either of you like to take over?

@creatorrr Sure, either I and/or @ryanprior would be happy to continue maintaining the work you started with this package. 

We are currently actively using mint and are both emacs users.

Should we open a mirror for `emacs-mint-mode` and then have you point in the README to the new project page where continued development and pull requests will be accepted?

**Comment by creatorrr** [comment]
That sounds good. I don’t know if people are using it already or not, in
which case, I could add you two as collaborators. What do you think?

**Comment by jgarte** [comment]
> That sounds good. I don’t know if people are using it already or not, in which case, I could add you two as collaborators. What do you think?
> […](#)

Sure,  that's fine to add us as collaborators.

I spoke with @ryanprior and we decided that I can maintain the project with the community at my sourcehut forge:

https://git.sr.ht/~jgart/emacs-mint-mode

Is that ok with you?

Some future plans for development are language server protocol support, packaging `emacs-mint-mode` for [guix](http://guix.gnu.org/) (I am an active guix maintainer and packager), and continued work on the features mentioned in the [planned roadmap](https://github.com/creatorrr/emacs-mint-mode#planned-roadmap) that you had created.

We recently worked on this mint project that leverages the web audio api:

https://carlacao.gitlab.io/joeys-garden-web-audio/

Here's the source code for it:

https://gitlab.com/carlacao/joeys-garden-web-audio

We're currently working on this [dnd](https://en.wikipedia.org/wiki/Dungeons_%26_Dragons) web app in mint/crystal:

https://github.com/ryanprior/lutrine-dice

**Comment by creatorrr** [comment]
That sounds great, @jgarte! I have added you as a collaborator to this repo so feel free to update it if you need to. Let me know how I can help. :)

**Comment by jgarte** [comment]
> That sounds great, @jgarte! I have added you as a collaborator to this repo so feel free to update it if you need to. Let me know how I can help. :)

Great! I accepted the invited.

Ok, I will maintain the project here and just keep a mirror at sourcehut since you made me a collaborator. That's fine with me. Thank you!

**Comment by bnsv** [comment]
Hi all. I am a newbie on both emacs and mint. Is there any chance to install this mint mode without straight.el? I am hesitate to use straight-el cause I am afraid it will conflicted with other setting. I am waiting for the MELPA released so I can easily install it.

**Comment by ryanprior** [comment]
I installed it without straight, @bnsv. I did this by cloning the repository into my system, adding that directory to my elisp load-path, and requiring the file.

**Comment by bnsv** [comment]
Thanks a lot @ryanprior . Now it works.
![Screenshot from 2021-06-27 20-49-23](https://user-images.githubusercontent.com/25299811/123547220-2029c880-d78a-11eb-824e-c1635c5fd381.png)

**Comment by ryanprior** [comment]
Congrats @bnsv, looking good! Can you add these instructions for installing without straight.el to the README? I'm sure @jgarte would accept a pull request to improve the docs. Let me know if you need help.
