### ISSUE TITLE
Mint homepage url has bad cert

### ISSUE THREAD

**Issue by jgarte** [creatorrr/emacs-mint-mode#4]
Hi @creatorrr 

The mint website link on the front page of this repo has a bad cert.

I changed it in the README. See [this commit](https://github.com/creatorrr/emacs-mint-mode/commit/8a25bc63885ec98deb61512ad503562218cbb774).

I don't have access to change it from the Code page of this repo. When you get a chance would you be able to update it?

Thank you! Hope all is well 😄

**Comment by creatorrr** [comment]
Done! :)
