### ISSUE TITLE
emacs lsp mode support for mint lang was merged.

### ISSUE THREAD

**Issue by zw963** [creatorrr/emacs-mint-mode#8]
https://github.com/emacs-lsp/lsp-mode/issues/3678#event-7219314539

The issue is, language server include format on save feature, so, it more appropriate if disable before_save_hook for emacs-mint-mode.

In fact, current format before save feature not work as discuss in #5 

```diff
diff --git a/mint-mode.el b/mint-mode.el
index 31a8a57..9061e3d 100644
--- a/mint-mode.el
+++ b/mint-mode.el
@@ -272,9 +272,6 @@
   ;; Register auto complete fn
   (push 'mint-keyword-completion-at-point completion-at-point-functions)
 
-  ;; hook for formatting on save
-  (add-hook 'mint-mode-hook (lambda () (add-hook 'after-save-hook #'mint-format-file nil 'local)))
-
   ;; For correctly formatting ansi terminal color codes
   (add-to-list 'comint-output-filter-functions 'ansi-color-process-output)
   (add-hook 'compilation-mode-hook 'ansi-color-for-comint-mode-on)
```

**Comment by jgarte** [comment]
Hi @zw963, can we close this issue?

How is `lsp-mode` working for you now with `emacs-mint-mode` after recent changes in `v1.0.3`?

**Comment by zw963** [comment]
> Hi @zw963, can we close this issue?

Yes, i will.


> 
> How is `lsp-mode` working for you now with `emacs-mint-mode` after recent changes in `v1.0.3`?

Totally same as any others mode which support lsp.

```cl
(require 'lsp-mode)

;;  ... many user preferred config for lsp-mode here

(add-hook 'mint-mode-hook
          (lambda ()
            (add-hook 'before-save-hook #'lsp-format-buffer t t)
            (lsp-deferred)
            ))
```
