### ISSUE TITLE
Result highlight issue

### ISSUE THREAD

**Issue by zw963** [creatorrr/emacs-mint-mode#9]
Please check following screenshot.

![image](https://user-images.githubusercontent.com/549126/186220176-29c38da9-6478-485e-a72c-60f851c8e111.png)

Result should only be highlight when use like this: `Result(error, value)`, it should not be highlight when use in `toResult`.

**Comment by zw963** [comment]
I fixed this in my PR too. 

https://github.com/creatorrr/emacs-mint-mode/pull/6/commits/54fd0dcebd8d0c2364be78fa2073b76bea4be40f

**Comment by creatorrr** [comment]
Merged this one. cc/ @jgarte
